# Generated by Django 3.0.7 on 2021-05-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0002_auto_20210515_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_message',
            name='m_url',
            field=models.CharField(blank=True, default='URL', max_length=1000),
        ),
    ]
