# Generated by Django 3.0.7 on 2021-05-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0003_auto_20210521_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_message',
            name='m_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
