# Generated by Django 3.0.7 on 2021-05-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0005_user_message_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_message',
            name='unique_msg_id',
            field=models.CharField(default='NULL', max_length=35),
        ),
    ]
