# Generated by Django 3.0.7 on 2021-05-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0006_user_message_unique_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_message',
            name='unique_msg_id',
            field=models.CharField(default='', max_length=35),
        ),
    ]
