# Generated by Django 3.0.7 on 2021-05-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0007_auto_20210525_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_message',
            name='unique_msg_status',
            field=models.CharField(default='read', max_length=10),
        ),
    ]
