# Generated by Django 3.0.7 on 2021-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0011_auto_20210526_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='reset_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_message',
            name='timestamp1',
            field=models.DateTimeField(),
        ),
    ]
