# Generated by Django 3.0.7 on 2021-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0012_auto_20210526_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='kwiqreply_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='wa_pass',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='wa_user_pass_base',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='wa_username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
