# Generated by Django 3.0.7 on 2021-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0013_auto_20210526_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_message',
            name='user_message_token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
