# Generated by Django 3.0.7 on 2021-05-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0015_auto_20210526_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_message',
            name='unique_msg_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
