# Generated by Django 3.2.3 on 2021-06-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0016_auto_20210529_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile',
            name='page_no',
            field=models.IntegerField(default=1),
        ),
    ]
